"""Regenerate deterministic local GIF fixtures and independent Pillow pixel oracles.
Requires Pillow only for regeneration; build/runtime use the checked-in files.
"""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "fixtures"
OUT.mkdir(exist_ok=True)

def animation(name, size, count, background):
    frames = []
    for i in range(count):
        frame = Image.new("RGB", size, background)
        draw = ImageDraw.Draw(frame)
        draw.rectangle((i * 3 % (size[0] - 24), 20, i * 3 % (size[0] - 24) + 20, 40), fill="black")
        draw.text((8, 6), name.upper(), fill="white")
        frames.append(frame)
    frames[0].save(OUT / (name + ".gif"), save_all=True, append_images=frames[1:],
                   duration=[1500] + [80] * (count - 1), loop=0, disposal=1, optimize=False)

animation("a", (128, 96), 8, (0, 160, 200))
animation("b", (256, 192), 48, (230, 100, 0))
Image.new("RGB", (24, 16), (160, 30, 220)).save(OUT / "single.gif")
Image.new("RGB", (64, 64), (160, 30, 220)).save(OUT / "static.png")
palette = [255, 0, 255, 0, 0, 0, 255, 255, 255, 20, 200, 40] + [0] * (768 - 12)
frames = []
for i in range(4):
    frame = Image.new("P", (64, 48), 0)
    frame.putpalette(palette)
    draw = ImageDraw.Draw(frame)
    draw.rectangle((4 + i * 10, 4, 12 + i * 10, 25), fill=1 if i % 2 == 0 else 3)
    draw.rectangle((4, 35, 50, 40), fill=2)
    frames.append(frame)
frames[0].save(OUT / "alpha.gif", save_all=True, append_images=frames[1:], transparency=0,
               duration=[0, 10, 20, 200], disposal=[1, 2, 3, 1], loop=0, optimize=False)
(OUT / "bad.gif").write_bytes(b"not a gif at all")
(OUT / "truncated.gif").write_bytes((OUT / "b.gif").read_bytes()[:-9])
(OUT / "empty.gif").write_bytes(b"GIF89a\x01\x00\x01\x00\x00\x00\x00;")
# Structurally valid GIF, invalid LZW code size/data. Exercise giflib's error path.
raw = bytearray((OUT / "single.gif").read_bytes())
pos = 13 + (3 << ((raw[10] & 7) + 1))
assert raw[pos] == 0x2c
pos += 10
if raw[pos - 1] & 0x80:
    pos += 3 << ((raw[pos - 1] & 7) + 1)
raw[pos + 2:pos + 2 + raw[pos + 1]] = b"\xff" * raw[pos + 1]
(OUT / "lzw.gif").write_bytes(raw)

header = ['// Generated by generate_fixtures.py; do not edit.', '#pragma once', '#include <span>',
          'struct GifFixture { const char* name; std::span<const uint8_t> bytes; int width, height; std::span<const uint32_t> hashes; std::span<const int> delays; };']
for name in ("a", "b", "single", "alpha", "bad", "truncated", "empty", "lzw"):
    header += [f'constexpr uint8_t {name}Bytes[] = {{', f'#embed "fixtures/{name}.gif"', '};']
    if name in ("bad", "truncated", "empty", "lzw"):
        continue
    hashes, delays = [], []
    with Image.open(OUT / (name + ".gif")) as gif:
        for i in range(gif.n_frames):
            gif.seek(i)
            pixels = bytearray(gif.convert("RGBA").transpose(Image.Transpose.FLIP_TOP_BOTTOM).tobytes())
            # RGB of a fully transparent pixel is immaterial. Canonicalize it.
            for j in range(0, len(pixels), 4):
                if pixels[j + 3] == 0:
                    pixels[j:j + 3] = b"\0\0\0"
            h = 2166136261
            for byte in pixels:
                h = ((h ^ byte) * 16777619) & 0xffffffff
            hashes.append(h)
            delay = gif.info.get("duration", 0)
            delays.append(100 if delay <= 10 else delay)
    header += [f'constexpr uint32_t {name}Hashes[] = {{' + ','.join(map(str, hashes)) + '};',
               f'constexpr int {name}Delays[] = {{' + ','.join(map(str, delays)) + '};']
header += ['constexpr GifFixture gifFixtures[] = {']
for name in ("a", "b", "single", "alpha"):
    with Image.open(OUT / (name + ".gif")) as gif:
        header += [f'{{"{name}", {name}Bytes, {gif.width}, {gif.height}, {name}Hashes, {name}Delays}},']
for name in ("bad", "truncated", "empty", "lzw"):
    header += [f'{{"{name}", {name}Bytes, 0, 0, {{}}, {{}}}},']
header += ['};']
(ROOT / "GifFixtures.hpp").write_text("\n".join(header) + "\n")
