// Generated by generate_fixtures.py; do not edit.
#pragma once
#include <span>
struct GifFixture { const char* name; std::span<const uint8_t> bytes; int width, height; std::span<const uint32_t> hashes; std::span<const int> delays; };
constexpr uint8_t aBytes[] = {
#embed "fixtures/a.gif"
};
constexpr uint32_t aHashes[] = {4265550774,3011041030,2928212886,2693667366,784292086,3476079174,1403191766,841608038};
constexpr int aDelays[] = {1500,80,80,80,80,80,80,80};
constexpr uint8_t bBytes[] = {
#embed "fixtures/b.gif"
};
constexpr uint32_t bHashes[] = {3812146489,9483461,3117050089,3246835845,2709127209,369319093,4187619737,543151093,3138010201,3624084197,2153208777,1547371557,2123841929,2057378389,1066230521,2543245077,2281344313,2263555013,3702016489,3451573637,3761208873,221445813,1240702105,1551049205,2506628697,3364611045,1648107977,3909467429,1374849161,2467140693,1922839033,4140869397,167885625,1780607941,4171147753,2759169157,2761105705,3126804405,1161947545,2427912181,4078151769,634084069,2308458953,3952344101,90531209,340089173,3791468281,1693511957};
constexpr int bDelays[] = {1500,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80};
constexpr uint8_t singleBytes[] = {
#embed "fixtures/single.gif"
};
constexpr uint32_t singleHashes[] = {2793914821};
constexpr int singleDelays[] = {100};
constexpr uint8_t alphaBytes[] = {
#embed "fixtures/alpha.gif"
};
constexpr uint32_t alphaHashes[] = {347112861,449308109,1924621725,2662012813};
constexpr int alphaDelays[] = {100,100,20,200};
constexpr uint8_t badBytes[] = {
#embed "fixtures/bad.gif"
};
constexpr uint8_t truncatedBytes[] = {
#embed "fixtures/truncated.gif"
};
constexpr uint8_t emptyBytes[] = {
#embed "fixtures/empty.gif"
};
constexpr uint8_t lzwBytes[] = {
#embed "fixtures/lzw.gif"
};
constexpr GifFixture gifFixtures[] = {
{"a", aBytes, 128, 96, aHashes, aDelays},
{"b", bBytes, 256, 192, bHashes, bDelays},
{"single", singleBytes, 24, 16, singleHashes, singleDelays},
{"alpha", alphaBytes, 64, 48, alphaHashes, alphaDelays},
{"bad", badBytes, 0, 0, {}, {}},
{"truncated", truncatedBytes, 0, 0, {}, {}},
{"empty", emptyBytes, 0, 0, {}, {}},
{"lzw", lzwBytes, 0, 0, {}, {}},
};
